name: KotlinMc
version: '${project.version}'
main: me.leandecks.kotlinmc.KotlinMc
api-version: '1.20'

commands:
  hallo:
    description: Greets the player
    usage: /<command>
  justday:
    description: Set time to just day
    usage: /<command>
  challenge:
    description: Starts the current challenge
    usage: /<command>